CFLAGS += -DBOARD_LAUNCHPAD=1

CONTIKI_TARGET_DIRS += launchpad common

BOARD_SOURCEFILES += board.c launchpad-sensors.c button-sensor.c xmem.c
BOARD_SOURCEFILES += ext-flash.c board-spi.c

### Signal that we can be programmed with cc2538-bsl
BOARD_SUPPORTS_BSL=1

ifeq ($(WITH_IP64),1)
    CFLAGS += -DUIP_FALLBACK_INTERFACE=ip64_uip_fallback_interface
    BOARD_SOURCEFILES += enc28j60-arch-spi.c
    MODULES += arch/dev/enc28j60
endif
